name: deploy-s3

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'

defaults:
  run:
    working-directory: packages/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: "123123123"
          AWS_SECRET_ACCESS_KEY: "asdfasdfadsdfasdfsadfasdfsdaf"
          AWS_DEFAULT_REGION: "us-east-1"
